typography_spectrum: 0
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.10591369052417576
  lightness: 0
  saturation: 0.3789885693695396
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Walmer House
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Walmer House Foundation
purpose: []
