layout_spectrum: 1
typography_spectrum: 0.03969200374558568
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.4449798765126616
  lightness: 0.046619262313470244
  saturation: 0.6017112482804805
  rhythmicContrast: 0.6607441166415811
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Walmer House
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Walmer House Foundation
description: ''
purpose: []
